# Generated by Django 3.0.5 on 2021-01-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogsBook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
