# Generated by Django 3.0.5 on 2021-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timeCreated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
